### ISSUE TITLE
Rename this "gato-control" repo to NEKO

### ISSUE THREAD

**Issue by henryj18** [ManifoldRG/NEKO#15]
Rename this "gato-control" repo to NEKO, and rename the other already-existing NEKO repo to something like "NEKO-Planning"

We need to rename "gato-control" repo to NEKO because NEKO is the project name, and most of the code is under this "gato-control" repo, the current NEKO repo only has some issues and README file.

This renaming strategy will put our codebase into the proper repo and yet avoid the hassle of merging two repos

**Comment by daniellawson9999** [comment]
This sounds good, maybe we can make this change tomorrow.

**Comment by henryj18** [comment]
The best solution is just to keep one repo, the "gato-control" that is renamed as "NEKO", and merge the issues from the original NEKO to this newly renamed NEKO (if it is not too much effort)

**Comment by harshsikka** [comment]
Done!
