### ISSUE TITLE
GATO paper tokenizing of Discrete values might be problematic

### ISSUE THREAD

**Issue by henryj18** [ManifoldRG/NEKO#16]
According to the paper:

1. Text is encoded via SentencePiece (Kudo & Richardson, 2018) with 32000 subwords into the integer
range [0, 32000).

2. Image .....

3. Discrete values, e.g. Atari button presses, are flattened into sequences of integers in row-major order.
The tokenized result is a sequence of integers within the range of [0, 1024).

4. Continuous values, e.g. proprioceptive inputs or joint torques ..... then discretized to 1024 uniform bins. The discrete integers
are then shifted to the range of [32000, 33024).

The ranges of item 1: [0, 32000) and 3: [0, 1024) collide on the first 1024 tokens, the ranges of item 1: [0, 32000) and 4: [32000, 33024) meet with each other seamlessly and do not collide. Item 1 and item 3 ranges should avoid collision as item 1 and 4. I am not sure whether it is a typo in the paper and GATO implementation has avoided the collision?  

In my opinion, we should avoid such collision in our NEKO implementation. For example, we could perhaps assign a range of [33024, 34048) to the 1024 tokens from discrete values, so we then have [0, 32000) + [32000, 33024) + [33024, 34048), 3 ranges meet seamlessly and no collision

If this is a valid proposal, we should review our codebase to make necessary corrections

I may need to submit a big fix to the GATO paper ?  :)

**Comment by harshsikka** [comment]
@henryj18 the paper definitely is confusing re: the tokenization of discrete values vs text. 

Thanks to @bhavul and @daniellawson9999, our implementation addresses this, see https://github.com/ManifoldRG/gato-control/blob/48bfaf3761c6e281499afbab30a54c059776f958/gato/policy/gato_policy.py#L58

**Comment by henryj18** [comment]
Ok, we have avoided the issue, not sure whether the GATO implementation avoided it or not, though

**Comment by harshsikka** [comment]
> Ok, we have avoided the issue, not sure whether the GATO implementation avoided it or not, though

the thing is, nobody knows what the original GATO implementation looks like 😂
