### ISSUE TITLE
Data audit & Inventory

### ISSUE THREAD

**Issue by helenlu66** [ManifoldRG/NEKO#37]
context: we want to document the data we already have, compare with the data we want => decide target dataset by the time we start experimentation

output: documentation on data we've already collected & identify gaps

**Comment by helenlu66** [comment]
Currently, we have:
[MS-COCO](https://drive.google.com/drive/folders/1r8sgrebm-_SNbpfDZ632NAADIrCdFVFh?usp=drive_link)
[Conceptual Captions](https://drive.google.com/drive/folders/1Iwsyb0gRU5uRXDXkJJxfqz0vVRkLx6__?usp=drive_link)
[OKVQA](https://drive.google.com/drive/folders/13AS_8FeY-L3cXthAfNmV0s8TzQSFih2g?usp=drive_link)
[VQAV2](https://drive.google.com/drive/folders/16g8RkmUZiCJcgBC49Ep-HoO2XDseraNS?usp=drive_link)
mentioned in [vision dataset availability analysis](https://docs.google.com/spreadsheets/d/18t38QKIMsZXiNxRcgDdKIxcrclPb5QEzvVKvGQBSJ98/edit#gid=1513169105)

**Comment by BobakBagheri** [comment]
Issue is already completed by my understanding from @snat-s 
Can you please add in your updates to this issue and then close the issue?

**Comment by harshsikka** [comment]
Closed
