### ISSUE TITLE
Dataset Tracker

### ISSUE THREAD

**Issue by harshsikka** [ManifoldRG/NEKO#39]
in ManifoldRG/NEKO_Archive#1, we included an analysis of several datasets and had an internal google sheet to covering this. 

We should keep a publicly interface-able dataset tracker, categorized by planned model release.

**Comment by harshsikka** [comment]
@helenlu66 I think this is related to ManifoldRG/NEKO#37 and can be merged/closed if you think it is worth it

**Comment by BobakBagheri** [comment]
Tracker to be created with all the datasets being investigated on issues shown above and a few other ManifoldRG/NEKO#53 , ManifoldRG/NEKO#52 , ManifoldRG/NEKO#51 
I understand @snat-s already has this tracker going, please add documentation update to this issue in the future to track changes as needed. 

One note, the dataset tracker should be accessible and easily understandable by the full community as well. We can discuss with @harshsikka as needed if there is significant action here. Hopefully it shouldn't change much on the formatting you are already using.

**Comment by harshsikka** [comment]
@snat-s please link the tracker in this issue

**Comment by BobakBagheri** [comment]
Closing, dataset reconciliation effort is captured in #56 so refer to this for all dataset related issues
