### ISSUE TITLE
Update Neko planning doc with Model Training / Evaluation Issues

### ISSUE THREAD

**Issue by harshsikka** [ManifoldRG/NEKO#42]
Document is found [here](https://docs.google.com/document/d/1XHuLaVpfMUZCwTKMiCo-rtK15ylKTdWqz9UGZOiaIkQ/edit?usp=sharing).

**Comment by BobakBagheri** [comment]
Preliminary document is complete above by Harsh
Needs update to new NEKO model scope as being defined by Harsh

@harshsikka this will be task to get to as soon as the NEKO model has been fully defined to you and team's plan, then can update document and leave it here. 

Expected outcome: Updated NEKO model "MVM" documented and shared here

**Comment by BobakBagheri** [comment]
Already captured #41
