### ISSUE TITLE
Multimodal Control Model Training

### ISSUE THREAD

**Issue by harshsikka** [ManifoldRG/NEKO#44]
@daniellawson9999 placeholder issue for the planned model training work we discussed. Please update with brief context for the team to understand motivation, plan, outcome. Feel free to break out into multiple issues if that is better.

**Comment by harshsikka** [comment]
@AmrMKayid sync with Daniel and Harsh to see how we can make this more generally usable and a foundation for future work

**Comment by harshsikka** [comment]
@daniellawson9999 moved this to in progress based on discord updates

**Comment by daniellawson9999** [comment]
https://github.com/daniellawson9999/gato-control

**Comment by daniellawson9999** [comment]
Training runs that have been performed so far on MuJoCo/Breakout can be found here: https://wandb.ai/daniellawson9999/gato-control/

**Comment by BobakBagheri** [comment]
Ready to close and be archived; Requested from @harshsikka to be reviewed by him before finalizing. 

Expecting a comment from harsh after review to start up next steps/link new issues.

**Comment by harshsikka** [comment]
This is definitely done - we are not training across all modalities in fact, and resolving bugs there. Closing.
