### ISSUE TITLE
Scope Cost of using existing Open Source Datasets: Conceptual Captions, QKVQA, VQAv2

### ISSUE THREAD

**Issue by atharva-tendle** [ManifoldRG/NEKO#50]
**Goal:**
----------------
We have verified that the following datasets are open-source: Conceptual Captions, QKVQA, and VQAv2.

We now want to estimate the cost of using these datasets in our implementation, this is subjective in nature and essentially entails an estimation of how complicated would it be to start at the links mentioned in this [sheet](https://docs.google.com/spreadsheets/d/18t38QKIMsZXiNxRcgDdKIxcrclPb5QEzvVKvGQBSJ98/edit#gid=1513169105) and end up with a data loader for each of the datasets.

**Output:**
----------------
Come up with a summary for each of the above datasets that discusses steps needed for us to take the raw data and use it for training.

Ideally, this issue will act as a foundation for follow-up implementation issues.

**Comment by harshsikka** [comment]
https://drive.google.com/drive/u/1/folders/1s5-DYf4PvyF6oS1hjcJJ2Jwipml6jvUK

**Comment by harshsikka** [comment]
@helenlu66 might be good to add status

**Comment by helenlu66** [comment]
the datasets are downloaded and the dataloaders are uploaded to the shared drive, but the data still need to be tokenized

**Comment by daniellawson9999** [comment]
Question, what do you think of the datasets used for flamingo, e.g. LAION and Multimodal C4 https://laion.ai/blog/open-flamingo/ ?

**Comment by BobakBagheri** [comment]
Need to create new issue based on work shown in thread @harshsikka 
Will close and move to archive after new issue is created and linked.

**Comment by harshsikka** [comment]
I think this issue is a little outdated - what is actionable is that we should do a review of the current datasets we have + sync w/ @snat-s's work tracking what datasets are useful. 

Another challenge is storing the data for testing/training + providing a dataset and benchmark.

**Comment by harshsikka** [comment]
Captured context in #56, closing
