### ISSUE TITLE
Investigate Alternative Datasets: LTIP

### ISSUE THREAD

**Issue by atharva-tendle** [ManifoldRG/NEKO#51]
**Goal:**
----------------
We want to investigate the LTIP dataset and find alternatives to this dataset. 
This investigation should consider the following aspects regarding the dataset:
- Nature of the dataset in terms of compatibility
- Size
- Memory Requirements (if possible)
- Ease of Integration

Use this [link](https://docs.google.com/spreadsheets/d/18t38QKIMsZXiNxRcgDdKIxcrclPb5QEzvVKvGQBSJ98/edit#gid=1513169105) as a starting point.

**Output:**
----------------
Come up with a dataset proposal for an alternative to the LTIP dataset and get it reviewed by the team.

**Comment by BobakBagheri** [comment]
Adding @snat-s for addition to current dataset organization effort

**Comment by snat-s** [comment]
# Context

From what I have read, a good alternative could be [COYO-700M](https://huggingface.co/datasets/kakaobrain/coyo-700m). It is a bit bigger than the original LTIP (300M). 

COYO is sourced from Common Crawl. Originally they collected 10B images but narrowed them down to this 700M.  

# Compatibility

The guys from Kakao actually trained several different models and showed that it is a good dataset.

> We empirically validated the quality of COYO dataset by re-implementing popular models such as [ALIGN](https://arxiv.org/abs/2102.05918), [unCLIP](https://arxiv.org/abs/2204.06125), and [ViT](https://arxiv.org/abs/2010.11929). 

They basically got the same results with this dataset. 

# Size
The size is 135GBs.

# Ease of integration

It is a dataset on HuggingFace so it should not be that difficult to integrate to the current pipeline.

**Comment by snat-s** [comment]
I am going to close this because I think this issue has been satisfied. More discussion about v0 can be found in #58.
