### ISSUE TITLE
Investigate Alternative Datasets: MassiveText

### ISSUE THREAD

**Issue by atharva-tendle** [ManifoldRG/NEKO#53]
**Goal:**
----------------
We want to investigate the MassiveText dataset and find alternatives to this dataset. 
This investigation should consider the following aspects regarding the dataset:
- Nature of the dataset in terms of compatibility
- Size
- Memory Requirements (if possible)
- Ease of Integration

Use this [link](https://docs.google.com/spreadsheets/d/18t38QKIMsZXiNxRcgDdKIxcrclPb5QEzvVKvGQBSJ98/edit#gid=1513169105) as a starting point.

**Output:**
----------------
Come up with a dataset proposal for an alternative to the MassiveText dataset and get it reviewed by the team.

**Comment by daniellawson9999** [comment]
In addition to considering those points, if we think the alternative of the Pile is a good choice, maybe we should reach out to Eleuther, who can potentially answer/provide some more points regarding our questions

**Comment by iNeil77** [comment]
In addition to The Pile, recent evidence (https://arxiv.org/abs/2210.07128) that LLMs trained on Code improve performance on reasoning tasks (that may have nothing to do with code) might suggest that training on (at least part of) The Stack (https://huggingface.co/datasets/bigcode/the-stack-dedup) might be a good idea.

**Comment by BobakBagheri** [comment]
Adding @snat-s for addition to current dataset organization effort

**Comment by BobakBagheri** [comment]
Closing, dataset reconciliation effort is captured in #56 so refer to this for all dataset related issues
